version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.13

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - run:
          name: Run Tests
          command: yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    context: NPM_REGISTRY
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  only_test:
    jobs:
      - test
      - deploy
        requires:
          - test
